steps:
- name: 'gcr.io/cloud-builders/git'
  args: [config, --list]  

- name: 'gcr.io/cloud-builders/git'
  args: [config, --list] 
  
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run','build']  

- name: 'gcr.io/reviews-236608/firebase'
  args: [target:apply, hosting, staging, reviews-staging] 

- name: 'gcr.io/reviews-236608/firebase'
  args: [deploy, --only, hosting] 

         
